[package]
name = "rscash"
version = "0.0.1"
authors = ["Gabriel Cardona <cgcardona@gmail.com>"]
edition = "2018"
description = "Rust crate for Bitcoin Cash"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.21.0"
bech32 = "0.7.1"
byteorder = "1.2"
bitcoin_hashes = "0.7"
bitcoinconsensus = { version = "0.17", optional = true }
serde = { version = "1", optional = true }
secp256k1 = "0.15"
hex = "=0.3.2"
